export const disclaimer = 'This independent awards program is not sponsored, endorsed, administered by, or associated with Meta, Facebook, or Instagram.';
export const platformNote = 'Facebook and Instagram are used only to describe the platforms where nominees publish their work.';

export type PlatformScope = 'facebook'|'instagram'|'both';
export const categories = [
{name:'Best Academic & Research Content',slug:'best-academic-research-content',platform:'both',description:'Recognizing creators who share educational, research-based knowledge for public benefit.',criteria:['Accuracy','Consistency','Educational value','Clarity','Public benefit']},
{name:'Best AI Literacy & Awareness Content',slug:'best-ai-literacy-awareness-content',platform:'both',description:'Recognizing creators making AI easier to understand for Ethiopian communities.',criteria:['Clarity','Responsible AI education','Practical use','Originality','Community value']},
{name:'Best Career & Professional Growth Content',slug:'best-career-professional-growth-content',platform:'both',description:'Recognizing creators improving careers and workplace readiness.',criteria:['Usefulness','Trust','Consistency','Career impact','Practical guidance']},
{name:'Best Child Development & Psychology Content',slug:'best-child-development-psychology-content',platform:'both',description:'Responsible content on parenting, learning, and psychology.',criteria:['Care','Accuracy','Accessibility','Safety','Public value']},
{name:'Best Mentorship & Community Support Content',slug:'best-mentorship-community-support-content',platform:'both',description:'Guiding and supporting communities through public content.',criteria:['Mentorship impact','Community response','Consistency','Generosity','Trust']},
{name:'Best Newsletter, Long-form, or Educational Series',slug:'best-newsletter-long-form-educational-series',platform:'both',description:'Regular educational series across long-form or episodic posts.',criteria:['Consistency','Structure','Usefulness','Depth','Audience benefit']},
{name:'Best STEM & Innovation Content',slug:'best-stem-innovation-content',platform:'both',description:'Promoting STEM, innovation, and digital skills.',criteria:['Originality','Clarity','Technical quality','Ethiopian relevance','Educational value']},
{name:'Health Advocate of the Year',slug:'health-advocate-of-the-year',platform:'both',description:'Responsible health and wellness education with public value.',criteria:['Responsible guidance','Public benefit','Consistency','Clarity','Trust']},
{name:'Consistent Creator of the Year',slug:'consistent-creator-of-the-year',platform:'both',description:'Useful and original community-centered consistent publishing.',criteria:['Consistency','Originality','Engagement quality','Trust','Audience value']},
{name:'Best Facebook Community Page',slug:'best-facebook-community-page',platform:'facebook',description:'Community-first Facebook pages and groups.',criteria:['Moderation quality','Helpfulness','Community trust','Consistency','Public value']},
{name:'Best Instagram Visual Storyteller',slug:'best-instagram-visual-storyteller',platform:'instagram',description:'Visual storytelling through reels, carousels, and images.',criteria:['Visual quality','Storytelling','Originality','Message clarity','Audience response']},
{name:'Best Reels Creator for Social Impact',slug:'best-reels-creator-for-social-impact',platform:'both',description:'Short-form creators educating and inspiring communities.',criteria:['Storytelling','Retention','Originality','Impact','Responsible content']},
{name:'Small Business Brand of the Year',slug:'small-business-brand-of-the-year',platform:'both',description:'Small businesses building trust and growth on social platforms.',criteria:['Brand clarity','Customer trust','Content quality','Consistency','Business value']},
{name:'Culture & Heritage Creator of the Year',slug:'culture-heritage-creator-of-the-year',platform:'both',description:'Preserving and celebrating Ethiopian culture and identity.',criteria:['Cultural value','Originality','Respect','Quality','Community response']},
{name:'Diaspora Voice of the Year',slug:'diaspora-voice-of-the-year',platform:'both',description:'Connecting Ethiopians globally through useful content.',criteria:['Connection','Relevance','Consistency','Public value','Authenticity']},
{name:'Changemaker of the Year',slug:'changemaker-of-the-year',platform:'both',description:'Highest recognition for cross-category impact and trust.',criteria:['Overall impact','Trust','Consistency','Originality','Public benefit']}
];

export const nominees=[{slug:'abeba-story-lab',name:'Abeba Story Lab',category:'best-instagram-visual-storyteller',city:'Addis Ababa',platform:['instagram'],votes:1240,impact:'Visual stories on education and culture.'},{slug:'addis-health-voice',name:'Addis Health Voice',category:'health-advocate-of-the-year',city:'Addis Ababa',platform:['facebook','instagram'],votes:1987,impact:'Trusted health explainers and prevention campaigns.'},{slug:'ethiotech-youth',name:'EthioTech Youth',category:'best-ai-literacy-awareness-content',city:'Bahir Dar',platform:['facebook'],votes:1432,impact:'AI literacy workshops and practical tools.'}];
